### ISSUE TITLE
v3 games todo

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#60]
- [x] Launch game with selected mods enabled https://github.com/SIXNetworks/withSIX-Platform/issues/4
 - This needs some consideration as often these games have launchers with mod enable/disable control, etc.
- [x] Remember mod/collection installed state - currently it will think there are updates/new install on refresh
- [x] Enable Update scans for updated and new content (currently we work with just the initial import)
 - [x] Enable automatically generating the updated json for api
- [x] Implement Download speed/progress reporting (waiting for Credentials decisions etc)
- [x] Show image/info in Library/QL (currently the info is missing)

Related:
- https://github.com/SIXNetworks/withSIX-Platform/issues/59

Soon:
- [ ] Implement claiming support
 - Add claimID to description?
 - Retrieve userID from Steam login
- [x] @Sonsalt , @ParaGraphicL Reconsider the Credentials Dialog (e.g become a Windows input dialog instead of from browser) #83
 - Alternatively we can hook into the X client to make it control the downloads, but it will be much work, and will reduce the experience in other ways.

- [ ] @Sonsalt , @ParaGraphicL Improve integration of the Info into the Mod Description on Detail pages
- [ ] @Sonsalt Investigate Dependencies
- [x] Support editing Tags properly (need to migrate from old Categories, to new Tags #62 )
 - idea for future: Categorizing tags)

Later:
- [x] Implement upload support (#64 + claiming?)

**Comment by Sonsalt** [comment]
@sickboy @ParaGraphicL 
Credentials dialogue, 
I am fine with this, for the user this would make little difference and it could help with the popup issue no? The importance is the reliability and the professionalism we show this :)

@sickboy 
I am not 100% sure what you mean, but when it comes to showing the Steam description it should indeed show as good as possible on our page. Only we need to show the link to the "Source" at the bottom or top. BI forum integration looks already quite good. For Stellaris and Starbound forum I think we will be equally able to show this easily. The banners shown in the Blog posts them selves should not be added to the gallery, but that is already covered in another topic.

@sickboy 
From my current investigation, neither Stellaris nor Starbound really use dependencies. I will of course have to look further. The bigger issue here might be conflicts. Steamworks has a way to show dependencies and it uses this in A3. If you ment just the way we show them on the page, this is a design element that I hope @ParaGraphicL can help solving.
